In [2]:
#   Copyright: © 2020 FRANCISCO JOSÉ MANTELL ZAMUDIO

import numpy as np
import pylab as pl

import pylab as pl
from matplotlib import pyplot as plt

from sympy.interactive import printing
from sympy import Symbol, Derivative, diff, simplify, solve
#Constantes
av, asup, ac, asym, apar = 16.0, 18.0, 0.72, 28.0, 34.0
hbarc , mp, mn, R0, c, h = 197.327, 938.272, 939.565, 1.23, 3e23, 6.62e-34

In [5]:
#Numeros masicos
A = [4,12,14]
#Numeros atomicos
Z = [86,2,6,6,84,80,80]
#Energias de ligadura
BRn, BPo, Balfa, BHg1, B12, BHg2, B14 = 1697.8, 1675.9, 28.295, 1629.3, 92.2, 1621.1, 105.284

In [6]:
#Calor de reaccion:
Q = [(BPo+Balfa-BRn), (BHg1+B12-BRn), (BHg2+B14-BRn)]
Q

[6.395000000000209, 23.700000000000045, 28.58400000000006]

In [9]:
#Masa
MASA = [(2*(mp+mn)-Balfa), (6*(mp+mn)-B12), ((6*mp)+(8*mn)-B14)]
Malfa = MASA[0]
M12 = MASA[1]
M14 = MASA[2]
#Radio nuclear
def R(y):
    r = R0*(y**(1/3))
    return r
R = R(220)
MASA, R

([3727.379, 11174.822, 13040.868000000002], 7.4252772062611525)

In [12]:
#masas del nucleo padre y los hijos:
MRn, MPo, MHg1, MHg2 = ((86*mp)+(134*mn)-BRn), ((84*mp)+(132*mn)-BPo), ((80*mp)+(128*mn)-BHg1), ((80*mp)+(126*mn)-BHg2)
#Masa reducida
mu = [((MPo*Malfa)/(MPo+Malfa)), ((MHg1*M12)/(MHg1+M12)), ((MHg2*M14)/(MHg2+M14))]
mu

[3659.5697934740415, 10565.285853884036, 12210.746641813243]

In [31]:
#Energia de la particula emitida
T = np.zeros(3)
V = np.zeros(6)
VC = np.zeros(6)
f = np.zeros(6)
for i in range(0,3):
    t = Q[i]+45
    T[i] =t
    #Velocidad
for j in range(0,3):
    t = T[j]
    m = MASA[j]
    v = np.sqrt((2*t)/m)*c
    vc = np.sqrt((2*t)/m)
    V[j] = v
    VC[j] = vc
#Frecuencia de colision
    frec = v/R
    f[j] = frec
for j in range(3,6):
    t =T[j-3]
    m = mu[j-3]
    v = np.sqrt((2*t)/m)*c
    vc = np.sqrt((2*t)/m)
    V[j] = v
    VC[j] = vc
    f[j] = v/R
    
f

array([6.70937767e+21, 4.48003743e+21, 4.29202287e+21, 6.77125234e+21,
       4.60745735e+21, 4.43551617e+21])

In [24]:
#Valor de e^2 en MeV*fm
e2 = hbarc/137.036
#Punto de corte con la barrera culombiana
R1 = np.zeros(3)
j = 0
for i in [168, 480, 480]:
    q = Q[j]
    r1 = i*e2/q
    R1[j] = r1
    j+=1
R1

array([37.82862649, 29.16384164, 24.1807671 ])

In [25]:
B = np.zeros(6)
#Factor de Gamow
G = np.zeros(6)
j = 0
for i in [168, 480, 480]:
    m = MASA[j]
    q = Q[j]
    rai = np.sqrt(2*m/(q*(hbarc**2)))
    x = R/R1[j]
    g = rai*i*e2*(np.arccos(np.sqrt(x))-np.sqrt(x*(1-x)))
    G[j] = g
    b = i*e2/R
    B[j] = b
    j+=1
    
j = 0
for i in [168, 480, 480]:
    m = mu[j]
    q = Q[j]
    rai = np.sqrt(2*m/(q*(hbarc**2)))
    x = R/R1[j]
    g = rai*i*e2*(np.arccos(np.sqrt(x))-np.sqrt(x*(1-x)))
    G[j+3] = g
    b = i*e2/R
    B[j+3] = b
    j+=1
B

array([32.5798027 , 93.08515057, 93.08515057, 32.5798027 , 93.08515057,
       93.08515057])

In [26]:
#Coeficiente de transmision
P = np.exp(-2*G)
#Probabilidad de desintegracion po unidad de tiempo
landa = f*P
landa

array([7.00624086e-05, 1.02169385e-35, 4.39163697e-27, 1.22147349e-04,
       3.87206212e-34, 1.61969524e-25])

In [27]:
#Vida mitad
tmitad = np.log(2)/landa
tmitad

array([9.89328221e+03, 6.78429437e+34, 1.57833442e+26, 5.67468049e+03,
       1.79012412e+33, 4.27949138e+24])

In [28]:
G

array([29.91195866, 65.21146736, 55.25057029, 29.63862773, 63.40803453,
       53.46316013])

In [29]:
P

array([1.04424601e-26, 2.28054757e-57, 1.02320913e-48, 1.80391076e-26,
       8.40390225e-56, 3.65164994e-47])

In [30]:
VC

array([0.1660633 , 0.11088507, 0.10623153, 0.16759475, 0.11403883,
       0.10978312])